---
title: "Code Book"
author: "Jim Milks"
date: "11/22/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Code Book
***
The run_analysis.R script downloads and prepares data following the five steps required  in the project's definition for the Final Project for the Getting and Cleaning Data course
***

1. Download and extract the original data into a folder named UCI HAR Dataset
2. Loads the training and test data sets and renames columns as needed for each variable
+features <- 561 rows, 2 columns. Original names of each variable
+activity_labels <- 6 rows, 2 columns. Codes and names of each activity performed by the volunteers.
+subject_train <- 7352 rows, 1 column. Data set containing data of the 30 volunteers in the study
+x_train <- 7352 rows, 561 columns containing data from smartphone gyroscopes and accelerometers as volunteers performed given activities. Used to train the machine learning algorithms
+y_train <- Code labels of the training data
+subject_test <- 2947 rows, 1 column containing data on the 30 volunteers
+x_test <- 2947 rows, 561 columns containing data from smartphone gyroscopes and accelerometers collected as 30 volunteers performed given activites. Used to test the marchine learning algorithms.
+y_test <- 2947 rows, 1 column contains test data code labels

3. Merges the training and test data sets together to form a single data set
+x 10299 rows and 561 columns created by rbinding the x_train and x_test data sets
+y 10299 rows and 1 column created by rbinding the y_train and y_test data sets
+subject 10299 rows and 1 column created by rbiding the subject_train and subject_test data sets
+full 10299 rows and 563 columns created by cbinding subject, y, and x

4. Extracts the measurements of the mean and standard deviation
+measurement 10299 rows and 88 columns created using dplyr to select the subject, code, and any columns containing "mean" and "std" in the column names

5. Uses descriptive names for each activity
+Exchanges the number activity codes for the actual names of each activity

6. Labels each variable in the data set with an descriptive name
+Replaced abbreviations in the column names with full names throughout the data set

7. Created a second data set listing the means of each activity grouped by subject.
+finished (180 rows, 88 columns) lists the means of each activity grouped by the individual subject performing the activity.
+final data exported as FinishedData.txt